routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('/login', 'Auth\LoginController@showLoginForm');

Auth::routes();

Route::get('users', 'UserController@index')->name('users.index');
Route::delete('users/{user}', 'UserController@destroy')->name('users.destroy');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/data', 'DataController@index')->name('data');
Route::get('/office', 'OfficeController@index')->name('office');

Route::resource('products', 'ProductController')->middleware('auth');

Route::resource('clients', 'ClientController')->middleware('auth');

Route::resource('sales', 'SaleController')
    ->except(['update', 'edit'])
    ->middleware('auth');

Route::resource('categories', 'CategoryController')
    ->except(['update', 'edit', 'show'])
    ->middleware('auth');

Route::get('/reports/sales', 'SaleController@export')->name('reports.sales')
    ->middleware('auth');

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    protected $primaryKey = 'rfc';
    public $incrementing = false;

    protected $fillable = [
        'rfc', 'name', 'email', 'phone', 'address'
    ];

    // This model can generate 1 or N sales
    public function sales() {
        return $this->hasMany('App\Sale', 'sale_id');
    }


}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Client;
use App\Http\Requests\ClientRequest;
use Illuminate\Http\Request;

class ClientController extends Controller
{
    /*
     * Display a listing of the resource.
     */
    public function index()
    {
        $clients = Client::latest()->get();
        return view('clients.index', compact('clients'));
    }

    /*
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('clients.create');
    }

    /*
     * Store a newly created resource in storage.
     */
    public function store(ClientRequest $request)
    {

        Client::create($request->all());

        return back()->with('created', true);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function show(Client $client)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function edit(Client $client)
    {
        return view('clients.edit', compact('client'));
    }

    /*
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function update(ClientRequest $request, Client $client)
    {
        $client->update($request->all());

        return redirect()->route('clients.index')->with('updated', true);
    }

    /*
     * Remove the specified resource from storage.
     */
    public function destroy(Client $client)
    {
        $client->delete();
        return back()->with('deleted', true);
    }
}

resources/views/clients/index.blade.php
@extends('layouts.app') @section('content') 
<div class="content-header mt-5">
  <div class="container text-center lead">
    <h1 x-text="cs" class="m-0 text-dark">Customer</h1>
    <p x-text="cdmb"></p>
    <a class="btn btn-dark btn-lg" x-text="ncsa" href="{{ route('clients.create') }}"> New Customer </a> @if(session('updated')) <div class="row">
      <div class="col-12">
        <div class="alert alert-success"> Success Update Customer</div>
      </div>
    </div> @endif @if(session('deleted')) <div class="row">
      <div class="col-12">
        <div class="alert alert-success"> Customer Deleted</div>
      </div>
    </div> @endif
  </div>
</div>
<div class="content">
  <div class="container-fluid">
    <div class="row"> @foreach($clients as $client) <div class="col-sm-12 col-md-3 text-center p-3 p-md-5">
        <div class="card text-center">
          <div class="card-body bg-dark text-white rounded">
            <svg class="bi bi-people-fill" width="4em" height="4em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm-5.784 6A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1h4.216zM4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z" />
            </svg>
            <hr class="bg-white">
            <h5 class="card-title">{{ $client->name }}</h5>
            <hr class="bg-white">
            <a class="btn btn-warning btn-block" href="{{ route('clients.edit', $client) }}"> Edit </a>
            <br />
            <form action="{{ route('clients.destroy', $client) }}" method="POST"> @csrf @method('DELETE') <input onclick="return confirm('Yakin menghapus customer ?? ' + 'Hapus?');" type="submit" value="Delete" class="btn btn-danger btn-block">
            </form>
            <br />
          </div>
        </div>
      </div> @endforeach </div>
  </div>
</div> 
@endsection