routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('/login', 'Auth\LoginController@showLoginForm');

Auth::routes();

Route::get('users', 'UserController@index')->name('users.index');
Route::delete('users/{user}', 'UserController@destroy')->name('users.destroy');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/data', 'DataController@index')->name('data');
Route::get('/office', 'OfficeController@index')->name('office');

Route::resource('products', 'ProductController')->middleware('auth');

Route::resource('clients', 'ClientController')->middleware('auth');

Route::resource('sales', 'SaleController')
    ->except(['update', 'edit'])
    ->middleware('auth');

Route::resource('categories', 'CategoryController')
    ->except(['update', 'edit', 'show'])
    ->middleware('auth');

Route::get('/reports/sales', 'SaleController@export')->name('reports.sales')
    ->middleware('auth');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $primaryKey = 'category_id';

    protected $fillable = [
        'name'
    ];

    //This model groups 1 or N products
    public function products() {
        return $this->hasMany('App\Product');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\CategoryRequest;

class CategoryController extends Controller
{
    /*
     * Display a listing of the resource.
     *
     */
    public function index()
    {
        $categories = Category::orderBy('name', 'asc')->paginate();
        return view('categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CategoryRequest $request)
    {
        Category::create($request->all());
        return back()->with('created', true);
    }


    /*
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        return back()->with('deleted', true);
    }
}

resources/views/categories/create.blade.php
@extends('layouts.app') @section('content')<div class="content-header mt-5"><div class="container-fluid text-center lead"><svg class="bi bi-bag" width="4em" height="4em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M14 5H2v9a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V5zM1 4v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4H1z"/><path d="M8 1.5A2.5 2.5 0 0 0 5.5 4h-1a3.5 3.5 0 1 1 7 0h-1A2.5 2.5 0 0 0 8 1.5z"/></svg><h1 class="m-0 text-dark" x-text="cc"></h1>@if(session('created'))<div class="row"><div class="col-12"><div class="alert alert-success">Success create new categories</div></div></div>@endif</div></div><div class="content"><div class="container text-center lead"><div class="row"><div class="col-12 col-md-3 p-3 p-md-5"></div><div class="col-12 col-md-6 p-3 p-md-5"><form method="post" action="{{ route('categories.store') }}"><div class="card-body">@if($errors->any())<div class="alert alert-danger">@foreach($errors->all() as $error) - {{ $error }}<br>@endforeach</div>@endif<div class="form-group"><label for="name" x-text="cn"></label><input type="text" class="form-control" value="{{ old('name') }}" name="name" placeholder="Insert categories name" required></div>@csrf<button onclick='return confirm("Save this categories ??")' type="submit" x-text="sv" class="btn btn-dark btn-block btn-lg">Save</button></form></div></div></div></div>@endsection

resources/views/categories/index.blade.php
@extends('layouts.app') @section('content') <div class="content-header mt-5">
  <div class="container-fluid lead text-center">
    <h1 class="m-0 text-center" x-text="ct"></h1>
    <p x-text="ctndb"></p>
    <a class="btn btn-dark btn-lg" href="{{ route('categories.create') }}" x-text="cnct"></a> @if(isset($_SESSION['deleted'])) <div class="row">
      <div class="alert alert-success"> Success update data</div>
    </div> @endif
  </div>
</div>
<div class="content lead text-center">
  <div class="container-fluid"> {{ $categories->links() }}
    <div class="row"> @foreach($categories as $category) <div class="col-sm-12 col-md-3 p-3 p-md-5 text-white">
        <div class="card">
          <div class="card-body bg-dark rounded">
            <svg class="bi bi-bag" width="4em" height="4em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M14 5H2v9a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V5zM1 4v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4H1z" />
              <path d="M8 1.5A2.5 2.5 0 0 0 5.5 4h-1a3.5 3.5 0 1 1 7 0h-1A2.5 2.5 0 0 0 8 1.5z" />
            </svg>
            <hr class="bg-white">
            <h5 class="card-title">{{ $category->name }}</h5>
            <hr class="bg-white">
            <form action="{{ route('categories.destroy', $category) }}" method="POST"> @csrf @method('DELETE') <input onclick="return confirm('Are you sure to delete ' + ' ' + '');" type="submit" value="Delete" class="btn btn-danger btn-block">
            </form>
          </div>
        </div>
      </div> @endforeach {{ $categories->links() }}
    </div>
  </div> @endsection