routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('/login', 'Auth\LoginController@showLoginForm');

Auth::routes();

Route::get('users', 'UserController@index')->name('users.index');
Route::delete('users/{user}', 'UserController@destroy')->name('users.destroy');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/data', 'DataController@index')->name('data');
Route::get('/office', 'OfficeController@index')->name('office');

Route::resource('products', 'ProductController')->middleware('auth');

Route::resource('clients', 'ClientController')->middleware('auth');

Route::resource('sales', 'SaleController')
    ->except(['update', 'edit'])
    ->middleware('auth');

Route::resource('categories', 'CategoryController')
    ->except(['update', 'edit', 'show'])
    ->middleware('auth');

Route::get('/reports/sales', 'SaleController@export')->name('reports.sales')
    ->middleware('auth');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $primaryKey = 'product_id';

    protected $fillable = [
        'name', 'description', 'product_left', 'price', 'cost', 'category_id'
    ];

    // This model can exists in N carts
    public function carts() {
        return $this->belongsToMany('App\Cart', 'carts', 'sale_id');
    }

    public function getGetExtractAttribute() {
        return substr($this->description, 0, 50);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\ProductRequest;
use App\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $products = Product::latest()->paginate(6);

        return view('products.index', [
            'products' => $products
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $categories = Category::all();
        return view('products.create', compact('categories'));
    }

    /*
     *  Store a newly created resource in storage.
     */
    public function store(ProductRequest $request)
    {
        //Store the product
        Product::create($request->all());
        return back()->with('created', true);
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Product $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Product $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        $categories = Category::all();
        return view('products.edit', compact('product', 'categories'));
    }

    /*
    * Update the specified resource in storage.
     */
    public function update(ProductRequest $request, Product $product)
    {
        $product->update($request->all());

        return back()->with('updated', true);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Product $product)
    {
        $product->delete();
        return back()->with('error', false);
    }
}

resources/views/products/create.blade.php
@extends('layouts.app') @section('content')<div class="content-header"><div class="container lead text-center"><h1 class="m-0 text-dark"> New Product</h1> @if(session('created'))<div class="row"><div class="col-12"><div class="alert alert-success"> Success Update</div></div></div> @endif</div></div><div class="content"><div class="container-fluid lead"><div class="row"><div class="col-12 col-md-3 p-3 p-md-5"></div><div class="col-12 col-md-6 p-3 p-md-5"><form method="post" action="{{ route('products.store') }}"><div class="card-body"> @if($errors->any())<div class="alert alert-danger"> @foreach($errors->all() as $error) - {{ $error }} <br> @endforeach</div> @endif<div class="form-group"> <label for="name">Product</label> <input type="text" class="form-control" value="{{ old('name') }}" name="name" placeholder="Product Name" required></div><div class="form-group"> <label for="category_id">Categories</label> <select required name="category_id" class="form-control"><option value="">Select Categories</option> @foreach($categories as $category)<option value="{{ $category->category_id }}"> {{ $category->name }}</option> @endforeach </select></div><div class="form-group"> <label for="price">Sell Price</label> <input type="number" min="1" name="price" class="form-control" required></div><div class="form-group"> <label for="description">Description </label><textarea class="form-control" name="description">{{ old('description') }}</textarea></div><div class="form-group"> <label for="product_left">Inventori </label> <input type="number" min="1" name="product_left" class="form-control"></div><div class="form-group"> <label for="cost">Cost</label> <input type="number" min="1" name="cost" class="form-control"></div>@csrf <button onclick="return confirm('Save Product ?');" type="submit" class="btn btn-dark btn-block btn-lg">Save </button></form></div></div></div></div></div> @endsection

resources/views/products/index.blade.php
@extends('layouts.app') @section('content') <div class="content-header mt-5">
  <div class="container lead text-center">
    <h1 x-text="pd" class="m-0 text-dark text-center">Produck</h1>
    <p x-text="dbps">Data Produk</p>
    <a class="btn btn-dark btn-lg" x-text="cnpdt" href="{{ route('products.create') }}"> Create New Product </a>
  </div>
</div>
<div class="content">
  <div class="container-fluid lead text-center"> {{ $products->links() }}
    <div class="row"> @foreach($products as $product) <div class="col-sm-12 col-md-3 lead text-center text-white p-3 p-md-5">
        <div class="card">
          <div class="card-body bg-dark">
            <svg class="bi bi-box" width="4em" height="4em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M8.186 1.113a.5.5 0 0 0-.372 0L1.846 3.5 8 5.961 14.154 3.5 8.186 1.113zM15 4.239l-6.5 2.6v7.922l6.5-2.6V4.24zM7.5 14.762V6.838L1 4.239v7.923l6.5 2.6zM7.443.184a1.5 1.5 0 0 1 1.114 0l7.129 2.852A.5.5 0 0 1 16 3.5v8.662a1 1 0 0 1-.629.928l-7.185 2.874a.5.5 0 0 1-.372 0L.63 13.09a1 1 0 0 1-.63-.928V3.5a.5.5 0 0 1 .314-.464L7.443.184z" />
            </svg>
            <hr class="bg-white">
            <h5 class="card-title">{{ $product->name }}</h5>
            <p class="card-text"> {{ $product->get_extract }}</p>
            <hr class="bg-white">
            <a class="btn btn-warning btn-block" href="{{ route('products.edit', $product) }}"> Edit </a>
            <br />
            <form action="{{ route('products.destroy', $product) }}" method="POST"> @csrf @method('DELETE') <input onclick="return confirm('Delete Product ?? ' + '');" type="submit" value="Delete" class="btn btn-danger btn-block">
            </form>
          </div>
        </div>
      </div> @endforeach </div> {{ $products->links() }}
  </div> @endsection