routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('/login', 'Auth\LoginController@showLoginForm');

Auth::routes();

Route::get('users', 'UserController@index')->name('users.index');
Route::delete('users/{user}', 'UserController@destroy')->name('users.destroy');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/data', 'DataController@index')->name('data');
Route::get('/office', 'OfficeController@index')->name('office');

Route::resource('products', 'ProductController')->middleware('auth');

Route::resource('clients', 'ClientController')->middleware('auth');

Route::resource('sales', 'SaleController')
    ->except(['update', 'edit'])
    ->middleware('auth');

Route::resource('categories', 'CategoryController')
    ->except(['update', 'edit', 'show'])
    ->middleware('auth');

Route::get('/reports/sales', 'SaleController@export')->name('reports.sales')
    ->middleware('auth');

app/Sale.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Sale extends Model
{
    protected $table = 'sales';

    protected $primaryKey = 'sale_id';

    public $incrementing = true;

    protected $fillable = [
        'total', 'rfc', 'id', 'created'
    ];



    public function client() {
        return $this->belongsTo('App\Client', 'rfc');
    }

    // This model can exists in N carts
    public function carts() {
        return $this->belongsToMany('App\Cart', 'sales', 'sale_id',
                                    'sale_id', 'sale_id', 'sale_id')
            ;
    }

}

app/Http/Controllers/SaleController.php
<?php

namespace App\Http\Controllers;

use App\Cart;
use App\Client;
use App\Http\Requests\SaleRequest;
use App\Product;
use App\Sale;
use App\Exports\SalesExport;
use Maatwebsite\Excel\Facades\Excel;
use Illuminate\Http\Response;

class SaleController extends Controller
{
    /*
     * Display a listing of the resource.
     */
    public function index()
    {
        $sales = Sale::latest()->paginate();
        return view('sales.index', compact('sales'));
    }

    /*
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //Get the clients information
        $clients = Client::orderBy('rfc', 'DESC')->get();
        //Get the products information
        $products = Product::orderBy('name', 'DESC')->get();
        //Total of sales today
        $totalSalesPerDay = 0;
        $salesToday = Sale::select('total')->where('created', date('Y-m-d'))
            ->get();

        foreach ($salesToday as $sale) {
            $totalSalesPerDay += $sale->total;
        }

        return view(
            'sales.create',
            compact('clients', 'products', 'totalSalesPerDay')
        );
    }

    /*
     * Store a newly created resource in storage.
     */
    public function store(SaleRequest $request)
    {
        $sale = Sale::create(
            [
                'total'   => $request->input('total'),
                'rfc'     => $request->input('rfc'),
                'id'      => $request->input('id'),
                'created' => date('Y-m-d')
            ]
        );

        if (isset($sale)) {
            $productsArray = (array)json_decode($request->input('products'));
            $completed = [];
            //Get the products sales
            foreach ($productsArray as $index) {
                $cart = new Cart();
                $cart->sale_id = $sale->sale_id;
                $cart->product_id = $index->id;
                $cart->amount = $index->amount;
                $cart->created = date('Y-m-d');
                $cart->save();
                $completed[] = $cart;
            }

            if (count($productsArray) === count($completed)) {
                return new Response($completed, 201);
            }
        }
        return new Response('Cart was not filled', 500);
    }

    /*
     * Display the specified resource.
     */
    public function show(Sale $sale)
    {
        //Cart information
        $carts = Cart::where('sale_id', $sale->sale_id)->get();

        return view('sales.single', compact('sale', 'carts'));
    }

    /*
     * Returns a response with the file provided by SalesExport
     * */
    public function export()
    {
        if (Sale::all()->count() > 0) {
            return Excel::download(new SalesExport(), 'sales.xlsx');
        }
        return back();
    }

    /*
     * Remove the specified resource from storage.
     */
    public function destroy(Sale $sale)
    {
        try {
            $sale->delete();
        } catch (\Exception $e) {
            return back()->with('error', 'Error');
        }
        return back()->with('deleted', true);
    }
}

resources/views/sales/index.blade.php
@extends('layouts.app') @section('content')<div class="content-header"><div class="container-fluid lead text-center"><h1 class="m-0 text-dark" x-text="rpt"></h1><p x-text="rptdm"></p> <a class="btn btn-success btn-lg" x-text="xpr" href="{{ route('reports.sales') }}"> Export Report Details </a> @if(isset($_SESSION['deleted']))<div class="alert alert-success"> Success</div> @endif</div></div><div class="content"><div class="container-fluid lead text-center"><div class="row"> @foreach($sales as $sale)<div class="col-sm-12 col-md-4 p-3 p-md-5 text-center"><div class="card-body bg-dark text-white"> <svg class="bi bi-cart3" width="4em" height="4em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg"> <path fill-rule="evenodd" d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm7 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/> </svg><hr class="bg-white">Customer : {{ $sale->client->name }}<h4>Total: <br/>Rp.<strong>{{ $sale->total }}</strong></h4><p class="card-text"> Date: {{ date_format($sale->created_at, 'd-M-Y') }}</p> <a href="{{ route('sales.show', $sale) }}" class="btn btn-info btn-block"> View </a> <br/><form action="{{ route('sales.destroy', $sale) }}" method="POST" > @csrf @method('DELETE') <input onclick="return confirm('Delete ' + '??');" type="submit" value="Delete" class="btn btn-danger btn-block"></form></div></div> @endforeach</div> {{ $sales->links() }}</div></div> @endsection